{
 "title": "Progetto BD",
 "time": { "from": "2023-03-22T23:00:00.000Z", "to": "2023-03-22T23:01:20.000Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "telemetry.telemetry.find({}, {\"Speed\":1,\"_id\":0})",
     "query": "telemetry.telemetry.find({}, {Speed: 1, _id:0})"
    }
   ]
  },
  {
   "title": "Throttle",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "telemetry.telemetry.find({}, {\"Throttle\":1,\"_id\":0})",
     "query": "telemetry.telemetry.find({}, {Throttle: 1, _id:0})"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "RPM" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "telemetry.telemetry.find({}, {\"RPM\":1,\"_id\":0})",
     "query": "telemetry.telemetry.find({}, {RPM: 1, _id:0})"
    }
   ]
  },
  {
   "title": "Lap Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "telemetry.telemetry.find({}, {\"Time\":1,\"_id\":0}).sort({_id:-1}).limit(1)",
     "query": "telemetry.telemetry.find({}, {Time: 1, _id:0}).sort({_id:-1}).limit(1)"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "telemetry.telemetry.find({}, {\"nGear\":1,\"_id\":0})",
     "query": "telemetry.telemetry.find({}, {nGear: 1, _id:0})"
    }
   ]
  },
  {
   "title": "Brake",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "telemetry.telemetry.find({}, {\"Brake\":1,\"_id\":0})",
     "query": "telemetry.telemetry.find({}, {Brake: 1, _id:0})"
    }
   ]
  },
  {
   "title": "DRS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "telemetry.telemetry.find({}, {\"DRS\":1,\"_id\":0})",
     "query": "telemetry.telemetry.find({}, {DRS: 1, _id:0})"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "parsedQuery": "telemetry.telemetry.find({}, {Time: 1, Speed:1, _id:0})",
     "query": "telemetry.telemetry.find({}, {Time: 1, Speed:1, _id:0})"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "parsedQuery": "telemetry.telemetry.find({}, {RPM:1, Time:1, _id:0})",
     "query": "telemetry.telemetry.find({}, {RPM:1, Time:1, _id:0})"
    }
   ]
  },
  {
   "title": "Throttle & Brake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "parsedQuery": "telemetry.telemetry.find({}, {Throttle:1, Brake:1, Time:1, _id:0})",
     "query": "telemetry.telemetry.find({}, {Throttle:1, Brake:1, Time:1, _id:0})"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "parsedQuery": "telemetry.telemetry.find({}, {nGear:1, Time:1, _id:0})",
     "query": "telemetry.telemetry.find({}, {nGear:1, Time:1, _id:0})"
    }
   ]
  },
  {
   "title": "DRS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "parsedQuery": "telemetry.telemetry.find({}, {DRS:1, Time:1, _id:0})",
     "query": "telemetry.telemetry.find({}, {DRS:1, Time:1, _id:0})"
    }
   ]
  }
 ]
}